version: 2.1
aliases:

references:
  images:
    elixir: &ELIXIR_IMAGE heathmont/elixir-ci:1.14.0-otp-25-alpine

jobs:
  code_quality:
    docker:
      - image: *ELIXIR_IMAGE
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-test-{{ checksum "mix.lock" }}
            - v1-test-
      - run:
          command: mix deps.get
      - run:
          command: mix compile --all-warnings --warnings-as-errors
      - save_cache:
          key: v1-test-{{ checksum "mix.lock" }}
          paths:
            - deps
            - _build
      - run:
          command: mix format --check-formatted
      - run:
          command: mix surface.format --check-formatted
      - run:
          command: mix credo

workflows:
  version: 2
  workflow:
    jobs:
      - code_quality:
          context: global
