version: 2.1
aliases:

jobs:
  otp_release:
    docker:
      - image: heathmont/elixir-ci:1.14.0-otp-25-alpine
    environment:
      MIX_ENV: prod
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-{{ checksum "mix.lock" }}-{{ .Revision }}
            - v1-build-{{ checksum "mix.lock" }}-
            - v1-build-
      - run:
          name: Fetch dependencies
          command: mix setup
      - save_cache:
          key: v1-build-{{ checksum "mix.lock" }}-{{ .Revision }}
          paths:
            - .cache
            - deps
            - _build
            - ~/.mix
  check_code_quality:
    docker:
      - image: heathmont/elixir-ci:1.14.0-otp-25-alpine
    environment:
      MIX_ENV: prod
    steps:
      - checkout
      - restore_cache:
          keys:
            - v7-build-{{ checksum "mix.lock" }}-{{ .Revision }}
            - v7-build-{{ checksum "mix.lock" }}-
            - v7-build-
      - run:
          command: mix setup
      - run:
          command: mix format --check-formatted
      - run:
          command: mix compile --all-warnings --warnings-as-errors
      - run:
          command: mix credo
      - run:
          command: mix surface.format --check-formatted
      - run:
          command: mix test
  deploy:
    docker:
      - image: heathmont/elixir-ci:1.14.0-otp-25-alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ./
      - run:
          name: Docker login
          command: echo -e "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Setup robot SSH key
          command: |
            echo "$ROBOT_SSH_KEY" | base64 -d > $HOME/.ssh/id_rsa.robot && chmod 600 $HOME/.ssh/id_rsa.robot && ssh-add $HOME/.ssh/id_rsa.robot
            echo -e "Host *\n IdentityFile $HOME/.ssh/id_rsa.robot\n IdentitiesOnly yes" > $HOME/.ssh/config
      - run:
          name: Setup deploy tool auth
          command: echo "{\"user\":\"$DEPLOY_USER\", \"pass\":\"$DEPLOY_PASS\"}" > $HOME/.deploy_auth
      - run:
          name: Deploy
          command: scripts/deploy/stacks-deploy $CIRCLE_TAG
  

workflows:
  version: 2
  workflow:
    jobs:
      - otp_release:
          context: global
      - check_code_quality:
          context: global
